// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAB9pTy2LSHx9_SsySCnCHwhFMgSCWJgU',
    appId: '1:983451094521:web:a2b2c27c9bfe541e528128',
    messagingSenderId: '983451094521',
    projectId: 'flutter-tutorial-2999c',
    authDomain: 'flutter-tutorial-2999c.firebaseapp.com',
    storageBucket: 'flutter-tutorial-2999c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fmMGvmm1211sz7eCjej3z_SmiVvTTB4',
    appId: '1:983451094521:android:11dd2169265d4215528128',
    messagingSenderId: '983451094521',
    projectId: 'flutter-tutorial-2999c',
    storageBucket: 'flutter-tutorial-2999c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEVTmzmKHw2_q698a4veL1dL5ddzOSR-o',
    appId: '1:983451094521:ios:722bd033169e0757528128',
    messagingSenderId: '983451094521',
    projectId: 'flutter-tutorial-2999c',
    storageBucket: 'flutter-tutorial-2999c.appspot.com',
    iosClientId: '983451094521-9000ah9mar6l9kjce0p8p4l2n57l6hqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEVTmzmKHw2_q698a4veL1dL5ddzOSR-o',
    appId: '1:983451094521:ios:69a184a695d6cf88528128',
    messagingSenderId: '983451094521',
    projectId: 'flutter-tutorial-2999c',
    storageBucket: 'flutter-tutorial-2999c.appspot.com',
    iosClientId: '983451094521-0rt2nd7r42gohh1u0n4ornfq8r1sh05u.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
